package fr.keyser.evolutions;

public enum Trait {
    ALARM, CARNIVOROROUS, CLIMBER, COLLABORATIVE, DEFENSIVE_HORDE, DIGGER, EMBUSCADE, FATTY, FERTILE, FORAGING, HORNED, INTELIGGENT, LONG_NECK, PACK_HUNTER, SCAVENGER, SHELL, SYMBIOSE;
}